package uas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

public class guii extends javax.swing.JFrame {

    /**
     * Creates new form guii
     */
    public guii() {
        initComponents();
        load_tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        formnama = new javax.swing.JTextField();
        formid = new javax.swing.JTextField();
        formjenis = new javax.swing.JTextField();
        formrasa = new javax.swing.JTextField();
        formharga = new javax.swing.JTextField();
        formexp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("DATA OBAT");

        jLabel2.setText("NAMA OBAT");

        jLabel3.setText("ID OBAT");

        jLabel4.setText("JENIS OBAT");

        jLabel5.setText("RASA OBAT");

        jLabel6.setText("HARGA OBAT");

        jLabel7.setText("EXP OBAT");

        formid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formidActionPerformed(evt);
            }
        });

        tabeldata.setBackground(new java.awt.Color(204, 255, 255));
        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Obat", "ID Obat", "Jenis Obat", "Rasa Obat", "Harga Obat", "Exp Obat"
            }
        ));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        btntambah.setBackground(new java.awt.Color(204, 255, 255));
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(255, 255, 204));
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btntambah)
                        .addGap(51, 51, 51)
                        .addComponent(btnedit)
                        .addGap(55, 55, 55)
                        .addComponent(btnhapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(47, 47, 47))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(72, 72, 72))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4))
                                            .addGap(43, 43, 43))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(formnama, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(formid)
                                    .addComponent(formjenis)
                                    .addComponent(formrasa)
                                    .addComponent(formharga)
                                    .addComponent(formexp))))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(formnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(formid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(formjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(formrasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(formharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(formexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnedit)
                    .addComponent(btnhapus))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formidActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
 String sql ="delete from data_obat where id_obat ='"+formid.getText()+"'";
 java.sql.Connection 
conn=koneksi.configDB();
 java.sql.PreparedStatement 
pst=conn.prepareStatement(sql);
 pst.execute();
 JOptionPane.showMessageDialog(this, "berhasil di hapus");
 } catch (Exception e) {
 JOptionPane.showMessageDialog(this, 
e.getMessage());
 }
 load_tabel();
 clearForm();
        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        try {
 String sql = "INSERT INTO data_obat VALUES ('"+formnama.getText()+"','"+formid.getText()+"','"+formjenis.getText()+"','"+formrasa.getText()+"','"+formharga.getText()+"','"+formexp.getText()+"')";
 java.sql.Connection
conn=koneksi.configDB();
 java.sql.PreparedStatement
pst=conn.prepareStatement(sql);
 pst.execute();
 JOptionPane.showMessageDialog(null,"Penyimpanan Data Berhasil");
load_tabel();
clearForm();
 }
catch (Exception e) {
 JOptionPane.showMessageDialog(this,
e.getMessage());
 }
        
    }//GEN-LAST:event_btntambahActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
 String sql ="UPDATE data_obat SET namaobat = '"+formnama.getText()+"', id_obat = '"+formid.getText()+"', jenisobat = '"+formjenis.getText()+"', rasaobat = '"+formrasa.getText()+"', hargaobat = '"+formharga.getText()+"', expobat = '"+formexp.getText()+"' WHERE id_obat = '"+formid.getText()+"'";
 java.sql.Connection 
conn=koneksi.configDB();
 java.sql.PreparedStatement 
pst=conn.prepareStatement(sql);
 pst.execute();
 JOptionPane.showMessageDialog(null, "data berhasil di edit");
 } catch (Exception e) {
 JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
 }
 load_tabel();
 clearForm();

    }//GEN-LAST:event_btneditActionPerformed

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:
        int baris = tabeldata.rowAtPoint(evt.getPoint());
 String namaobat = tabeldata.getValueAt(baris,1).toString();
 formnama.setText(namaobat);
 String id_obat =tabeldata.getValueAt(baris,2).toString();
 formid.setText(id_obat);
 String jenisobat = tabeldata.getValueAt(baris,3).toString();
 formjenis.setText(jenisobat);
 String rasaobat = tabeldata.getValueAt(baris,4).toString();
 formrasa.setText(rasaobat);
 String hargaobat = tabeldata.getValueAt(baris,5).toString();
 formharga.setText(hargaobat);
 String expobat = tabeldata.getValueAt(baris,6).toString();
 formexp.setText(expobat);
    }//GEN-LAST:event_tabeldataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guii().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JTextField formexp;
    private javax.swing.JTextField formharga;
    private javax.swing.JTextField formid;
    private javax.swing.JTextField formjenis;
    private javax.swing.JTextField formnama;
    private javax.swing.JTextField formrasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeldata;
    // End of variables declaration//GEN-END:variables
private void clearForm(){
  formnama. setText ("");
  formid. setText ("");
  formjenis. setText ("");
  formrasa. setText ("");
  formharga. setText ("");
  formexp. setText ("");
  
}
    
    
    private void load_tabel() {
 {
    DefaultTableModel model = new 
    DefaultTableModel();
    model.addColumn("NO");
    model.addColumn("NAMA");
    model.addColumn("ID OBAT");
    model.addColumn("JENIS OBAT");
    model.addColumn("RASA OBAT");
    model.addColumn("HARGA OBAT");
    model.addColumn("EXP OBAT");
 //menampilkan data database kedalam tabel
 try {
 int no=1;
 String sql = "select * from data_obat";
 java.sql.Connection 
conn=koneksi.configDB();
 java.sql.Statement 
stm=conn.createStatement();
 java.sql.ResultSet 
res=stm.executeQuery(sql);
 while(res.next()){
 model.addRow(new 
Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
 }
 
    tabeldata.setModel(model);
 
       } 
      catch (SQLException e) {
      }
 }
}
}

 


